CREATE DATABASE CADASTROEVENTO;

USE CADASTROEVENTO;

CREATE TABLE EVENTO
(
    ID   BIGINT      NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL,
    DATA DATETIME    NOT NULL,

    PRIMARY KEY (ID)
);

INSERT INTO EVENTO (NOME, DATA)
VALUES ('Palestra João Silva', SYSDATE());

SELECT *
FROM EVENTO;
